# Generated by Django 6.0.4 on 2026-06-26 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Purchase cost in NPR', max_digits=10)),
                ('utility_value', models.IntegerField(help_text='Importance score 1–100')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-utility_value'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('optimized', 'Optimized'), ('purchased', 'Purchased')], default='optimized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimized_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_utility', models.IntegerField(blank=True, null=True)),
                ('budget_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_sessions', to=settings.AUTH_USER_MODEL)),
                ('selected_items', models.ManyToManyField(blank=True, related_name='procurement_sessions', to='inventory.procurementitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
