# Generated by Django 6.0.4 on 2026-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Mark as required - will be included in every optimization'),
        ),
    ]
