# Generated by Django 6.0.4 on 2026-06-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_procurementitem_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementitem',
            name='is_required',
        ),
    ]
