# Generated by Django 6.0.4 on 2026-06-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_latitude_room_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='room',
            name='longitude',
        ),
    ]
