# Generated by Django 6.0.4 on 2026-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_hostel_latitude_alter_hostel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
