# Generated by Django 6.0.4 on 2026-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_hostel_latitude_alter_hostel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
    ]
