# Generated by Django 6.0.4 on 2026-06-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_hostel_latitude_alter_hostel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.AddField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], default='non_ac', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='bathroom_type',
            field=models.CharField(choices=[('attached', 'Attached Bathroom'), ('shared', 'Shared Bathroom')], default='shared', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10),
        ),
    ]
