# Generated by Django 6.0.4 on 2026-06-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_remove_room_facilities_room_ac_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('entrance', 'Entrance'), ('block', 'Block'), ('floor', 'Floor'), ('room', 'Room'), ('common', 'Common Area')], max_length=20)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.block')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.floor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.room')),
            ],
            options={
                'db_table': 'hostel_location_node',
            },
        ),
        migrations.CreateModel(
            name='NodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('bidirectional', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='hostel.locationnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='hostel.locationnode')),
            ],
            options={
                'db_table': 'hostel_node_edge',
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
