# Generated by Django 6.0.4 on 2026-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_locationnode_nodeedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_purpose',
            field=models.CharField(choices=[('residential', 'Residential'), ('reception', 'Reception'), ('office', 'Office'), ('lobby', 'Lobby'), ('DI_room', 'DI Room'), ('library', 'Library'), ('canteen', 'Canteen'), ('hall', 'Hall')], default='residential', max_length=20),
        ),
    ]
