# Generated by Django 6.0.4 on 2026-06-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon', models.IntegerField(default=14)),
                ('history_json', models.JSONField()),
                ('forecast_json', models.JSONField()),
                ('moving_avg', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
