# Generated by Django 6.0.4 on 2026-05-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='discipline_strikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='friend_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_requested_by', to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='noise_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_habits',
            field=models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=20, null=True),
        ),
    ]
