# Generated by Django 6.0.4 on 2026-06-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_disability_support_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='perm_pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='temp_pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
